### ISSUE TITLE
Package nomenclature does not respect standard

### ISSUE THREAD

**Issue by marcandregirard** [Phrancis/PsychoProductionsAdminClient#1]
At the moment, your package seems to be capitalize which is not the [standard way](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html).

Main -> main
IndividualComponents ->individual.components

**Comment by Phrancis** [comment]
One quick question, should `individual.components` be a single package name, or is it intended to be a `components` package inside an `individual` package?

**Comment by marcandregirard** [comment]
it will be shown as a `components`package inside an `individual`. But it's not that important since you can have "empty" packages, containing others packages. You could use `individualcomponents` but it's hard to read.

**Comment by Phrancis** [comment]
OK thanks, I might just go with `components` for simplicity :+1:
